version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /root/data/jenkins_home:/var/jenkins_home   # Mount host directory into container
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:




sudo chmod -R 777 /root/data/jenkins_home
