# This yaml files launches Jenkins + Prometheus + Grafana collectively .

version: "3"
services:

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - $HOME/learning/jenkins/jenkins_home:/var/jenkins_home

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000